### ISSUE TITLE
Shedding too much Light on a Microcontroller's Firmware Protection

### ISSUE THREAD

**Issue by c0d3z3r0** [JohannesObermaier/f103-analysis#4]
Hi there,

are the sources/scripts from "Shedding too much Light on a Microcontroller's Firmware Protection" available anywhere? The site mentioned in the slides is not reachable anymore.

Thanks!

**Comment by JohannesObermaier** [comment]
Hi, for reasons unknown to me, the original page is currently unavailable.

You can find a version in the web archive
https://web.archive.org/web/20220408102806/https://www.aisec.fraunhofer.de/en/FirmwareProtection.html

It links to the following files which seem still to be available:
https://www.aisec.fraunhofer.de/content/dam/aisec/ResearchExcellence/microbootCrc.zip
https://www.aisec.fraunhofer.de/content/dam/aisec/ResearchExcellence/coldbootStepping.zip
https://www.aisec.fraunhofer.de/content/dam/aisec/ResearchExcellence/swdFirmwareExtractor.zip
https://www.aisec.fraunhofer.de/content/dam/aisec/Dokumente/Publikationen/Studien_TechReports/englisch/Biblio-Bibtex.bib
https://www.usenix.org/conference/woot17/workshop-program/presentation/obermaier

**Comment by c0d3z3r0** [comment]
Oops, I had checked google cache but forgot web archive :D Thanks!

**Comment by c0d3z3r0** [comment]
@JohannesObermaier Curious, did you try to do that SWD attack via OpenOCD (probably requires some patching)?

**Comment by rumpelsepp** [comment]
> Hi, for reasons unknown to me, the original page is currently unavailable.

We fixed the webpage. It is online again:

https://www.aisec.fraunhofer.de/en/FirmwareProtection.html
